### PR TITLE
add LICENSE

### LINKED ISSUE #201: Add LICENSE
The repository has no LICENSE. Please add an appropriate one.

### PR DESCRIPTION
**Pull request by fkr**
closes #201

### CODE REVIEW

**Comment by fkr** [comment]
ping @jschoone @garloff

**Comment by garloff** [comment]
OK, so this is CC-SA-4.0, a weak copyleft license. Correct? 
We have quite some docs under CC-BY-SA-4.0, which includes attribution.
Wondering whether that would be good here too.

**Comment by fkr** [comment]
> OK, so this is CC-SA-4.0, a weak copyleft license. Correct? We have quite some docs under CC-BY-SA-4.0, which includes attribution. Wondering whether that would be good here too.

It is the contents of:

https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt

**Review by garloff — APPROVED** [review]
CC-SA-4.0 looks good to me.

**Pull request merged**
