### PR TITLE
Cancel community call on 2022-11-10 due to the OSBA meeting

### PR DESCRIPTION
**Pull request by itrich**
Signed-off-by: Eduard Itrich <eduard@itrich.net>

### CODE REVIEW

**Comment by frosty-geek** [comment]
this is kinda outdated ;-)

**Comment by itrich** [comment]
> this is kinda outdated ;-)

That's only your point of view!

back-to-the-future

**Comment by itrich** [comment]
> this is kinda outdated ;-)

I'm referring to the community call in two weeks :smile:

**Review by fkr — APPROVED** [review]
LGTM!

**Pull request merged**
