### PR TITLE
Add a seperate calendar for OpenOps

### PR DESCRIPTION
**Pull request by itrich**
Signed-off-by: Eduard Itrich <eduard@itrich.net>

### CODE REVIEW

**Review by maxwolfs — APPROVED** [review]
lgtm!

**Review by maxwolfs — APPROVED** [review]
lgtm

**Comment by fkr** [comment]
I'm not really happy with this change. For once it feels to me that Open Operations is split away from SCS (since we speak about "The Open Operations community". 

The chosen slot people makes it fairly hard for people active in SCS to join:

SIG IAM and SIG Monitoring are directly before and after. Both are groups where operators are active and from which I hope people would join open operations related activities as well.
For the work on the manifesto (something that was said to be temporary) the slot was OK, since it was meant to move the manifesto forward in a small, dedicated group.

A place where we try to live the principles of open operations is the lean coffee as well as the product owner meetups I'm currently sketching out. How do these relate to this meeting?

**Comment by itrich** [comment]
> I'm not really happy with this change. For once it feels to me that Open Operations is split away from SCS (since we speak about "The Open Operations community".

We concluded that we urgently need to reach out to a way broader community in order to create awareness for our Open Operations paradigm among the industry. Thus, we should allow

- supporters/interests to subscribe to a dedicated mailing list
- supporters/interests to subscribe to a dedicated calendar

Yes, this creates a separate community which is not limited to our project. However, I perceive the SCS community as an integral part of this Open Operations community. For instance, the calendar entry will be still part of the public SCS calendar and I intend to add the `scs-tech` mailing list to the OpenOps mailing list.

> The chosen slot people makes it fairly hard for people active in SCS to join:
> 
> SIG IAM and SIG Monitoring are directly before and after. Both are groups where operators are active and from which I hope people would join open operations related activities as well. For the work on the manifesto (something that was said to be temporary) the slot was OK, since it was meant to move the manifesto forward in a small, dedicated group.

This is a completely different topic. I'm happy to find a new slot for the regular Open Ops meeting. Feel free to start a PR against the calendar with an alternative slot proposal.

> A place where we try to live the principles of open operations is the lean coffee as well as the product owner meetups I'm currently sketching out. How do these relate to this meeting?

All these initiatives count towards more openness in the domain of operations. Anyone is highly appreciated to join our regular meetings, start discussions or share great stories. But we need to respect that there is a world beyond SCS which we need to address and convince to abide with our principles.

**Pull request merged**
