### PR TITLE
as discussed, we're splitting the OPS-IAM Team call into two calls.

### PR DESCRIPTION
**Pull request by fkr**
The chosen timeslot has been proposed by the active members of the SIG IAM (@reqa, @jnull, @matfechner and @JuanPTM).
The board has been created, the pads are ready and the minutes directory will be created, when the first meeting happenend.

Signed-off-by: Felix Kronlage-Dammers <fkr@hazardous.org>

### CODE REVIEW

**Comment by fkr** [comment]
this is WIP. I'll write a mail to scs-tech sometime later today and point to this PR.

**Comment by itrich** [comment]
Is this ready to be reviewed and subsequently merged?

**Comment by matfechner** [comment]
@fkr LGTM

**Comment by fkr** [comment]
thanks @matfechner for looking at it.
@itrich now it is ready to be reviewed and merged. I wanted to allow for couple days of comments.

**Review by itrich — APPROVED** [review]
LGTM! Thank you for preserving the old schedule, which is very useful for browsing through history of meetings.

**Comment by itrich** [comment]
Somehow the old slot got lost. We'll have to investigate on this :disappointed:

**Pull request merged**
