### PR TITLE
remove AD from community call rotation

### PR DESCRIPTION
**Pull request by fkr**
requested by himself

### CODE REVIEW

**Review by jschoone — APPROVED** [review]

**Review by alexander-diab — APPROVED** [review]
lgtm!

**Comment by garloff** [comment]
I guess the (wrong) removal of historic information is due to a limitation of the software.
If this is effective immediately, it would be on someone else today (bhp?) to moderate today, which is very short notice.
I'm unhappy about this!

**Comment by fkr** [comment]
> I guess the (wrong) removal of historic information is due to a limitation of the software. If this is effective immediately, it would be on someone else today (bhp?) to moderate today, which is very short notice. I'm unhappy about this!

yes, this script was meant as simple way of organizing the rotation of the community call.

**Comment by fkr** [comment]
Kurt is not happy with this change, I'll just close the PR then.

**Comment by garloff** [comment]
FKR, I meant not to reject the PR.

**Pull request merged**
